#!/bin/sh
#setkblayout
setxkbmap -layout 'se,ar' -option 'grp:alt_caps_toggle'
# set root pointer
xsetroot -cursor_name left_ptr

# key bindings
sxhkd &

# wallpaper
nitrogen --restore &

# launch compton
al-compositor --start &

# xfce settings
xfsettingsd &

# panel
al-polybar-session &

# Set some bsp specific stuff
bspc monitor -d I II III IV V VI  
#VI VII VIII IX X

bspc config border_width 1
bspc config window_gap 12
bspc config top_padding 16
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config automatic_scheme alternate
#bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config honor_size_hints true
bspc config remove_unplugged_monitors true
bspc config split_ratio 0.54
bspc config borderless_monocle true
bspc config gapless_monocle true
#bspc config paddingless_monocle true
bspc config single_monocle true
bspc config pointer_modifier mod1
bspc config click_to_focus
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
#bspc config focus_follows_pointer true


bspc config external_rules_command ~/.config/bspwm/external-rules.sh
bspc rule -a thunar desktop=' ^1' state=floating follow=on
bspc rule -a 'Google chrome' desktop='^2'
bspc rule -a 'xfce4-screenshooter' state=floating center=on focus=on
bspc rule -a 'mpv' state=floating center=on focus=on
bspc rule -a 'gsimplecal' state=floating center=on focus=on
